#!/bin/bash

cat /tmp/rails.pid
echo "----------------"
yarn --version

yarn
echo "----------------"
echo "-----------------"

rails webpacker:install

#bundle exec rake db:setup

bundle exec rake db:migrate && \
bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/rails.pid
